# This is a basic workflow to help you get started with Actions

name: Build And Deploy App To Firebase Distribution

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: set up JDK 11
      - uses: actions/setup-java@v3
        with:
          java_version: '11'
          distribution: 'temurin'
          cache: gradle




      # Runs a single command using the runners shell
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew


      # Runs a set of commands using the runners shell
      - name: Build and Deploy Debug
        run:  ./gradlew assembleDebug appDistributionUploadDebug
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
